const COMPLIANCE_OFFICERS = [
  { value: "mannah", label: "Mannah" },
  { value: "hannah", label: "Hannah" },
  { value: "patrick", label: "Patrick" },
  { value: "uche", label: "Uche" },
  { value: "kumba", label: "Kumba" },
  { value: "francess", label: "Francess" },
];

const ISSUE_CATEGORIES = [
  { value: "needs_edit", label: "Needs Edit" },
  { value: "status_check", label: "Status check" },
  { value: "draft", label: "Draft" },
  { value: "under_pay", label: "Under pay" },
  { value: "needs_appointment", label: "Needs Appointment" },
  { value: "missing_application", label: "Missing Application" },
  { value: "information", label: "Information" },
  { value: "card_delay", label: "Card Delay" },
  { value: "on_spot", label: "On-spot" },
  { value: "wrong_photo", label: "Wrong photo" },
  { value: "approvals", label: "Approvals" },
  { value: "wrong_location", label: "Wrong Location" },
];

const ESCALATION_CONTACTS = [
  { value: "kaseem", label: "Kaseem" },
  { value: "janna", label: "Janna" },
  { value: "abdul_rahman", label: "Abdul Rahman" },
  { value: "mercy", label: "Mercy" },
  { value: "marwan", label: "Marwan" },
];

const DEFAULT_FORM_CONFIG = {
  title: "New Compliance Ticket",
  submitLabel: "Submit Ticket",
  fields: [
    {
      id: "applicantName",
      type: "text",
      label: "Client name",
      placeholder: "Full name",
      required: true,
      enabled: true,
      order: 0,
    },
    {
      id: "nin",
      type: "text",
      label: "NIN",
      placeholder: "National ID number",
      required: false,
      enabled: true,
      order: 2,
    },
    {
      id: "phoneNumber",
      type: "tel",
      label: "Contacts",
      placeholder: "Phone number",
      required: true,
      enabled: true,
      order: 3,
    },
    {
      id: "issueType",
      type: "select",
      label: "Issue category",
      placeholder: "Select category…",
      displayAs: "dropdown",
      allowMultiple: false,
      required: false,
      enabled: true,
      order: 4,
      options: ISSUE_CATEGORIES,
    },
    {
      id: "issueCategory2",
      type: "text",
      label: "Issue category 2",
      placeholder: "Optional secondary category",
      required: false,
      enabled: true,
      order: 5,
    },
    {
      id: "explanation",
      type: "textarea",
      label: "Issue Explained",
      placeholder: "Describe the issue",
      required: true,
      enabled: true,
      order: 6,
      rows: 4,
    },
    {
      id: "issueSolution",
      type: "textarea",
      label: "Issue solution",
      placeholder: "Resolution / next steps",
      required: false,
      enabled: true,
      order: 7,
      rows: 3,
    },
    {
      id: "calledDate",
      type: "date",
      label: "Called date",
      required: false,
      enabled: true,
      order: 8,
    },
    {
      id: "images",
      type: "images",
      label: "Upload images",
      helpText: "Optional attachments. Max 5MB each.",
      required: false,
      enabled: false,
      order: 9,
      maxCount: 2,
      maxSizeMb: 5,
      allowCamera: true,
    },
  ],
};

const CORE_FIELD_IDS = new Set([
  "complianceOfficer",
  "applicantName",
  "nin",
  "phoneNumber",
  "issueType",
  "issueCategory2",
  "explanation",
  "issueSolution",
  "calledDate",
  "images",
]);

module.exports = {
  DEFAULT_FORM_CONFIG,
  COMPLIANCE_OFFICERS,
  ISSUE_CATEGORIES,
  CORE_FIELD_IDS,
  ESCALATION_CONTACTS,
};
